# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visionX', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image_tags',
        ),
        migrations.DeleteModel(
            name='images',
        ),
        migrations.DeleteModel(
            name='tag',
        ),
    ]
