# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visionX', '0002_auto_20170804_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/images')),
            ],
        ),
    ]
