# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionX', '0003_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagFreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_Name', models.CharField(max_length=150)),
                ('tag_freq', models.IntegerField()),
            ],
        ),
    ]
