# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionX', '0004_tagfreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagfreq',
            name='tag_Name',
            field=models.CharField(max_length=150, verbose_name='Tag Name'),
        ),
        migrations.AlterField(
            model_name='tagfreq',
            name='tag_freq',
            field=models.IntegerField(verbose_name='Tag Freq'),
        ),
    ]
