# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visionX', '0005_auto_20170807_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagFreq',
        ),
    ]
