# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionX', '0006_delete_tagfreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagFreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_Name', models.CharField(max_length=150, verbose_name='Tag Name')),
                ('tag_freq', models.IntegerField(verbose_name='Tag Freq')),
            ],
        ),
    ]
