# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionX', '0007_tagfreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TempTagName', models.CharField(max_length=150, verbose_name='Tag Name')),
                ('TempTagFreq', models.IntegerField(verbose_name='Tag Freq')),
            ],
        ),
    ]
